// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tracker.Infrastructure.Persistence.Context;

#nullable disable

namespace Tracker.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CustomerType", b =>
                {
                    b.Property<int>("CustomerTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customer_type_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("description");

                    b.HasKey("CustomerTypeId");

                    b.ToTable("customer_types", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerTypeId = 1,
                            Description = "regular"
                        },
                        new
                        {
                            CustomerTypeId = 2,
                            Description = "vip"
                        },
                        new
                        {
                            CustomerTypeId = 3,
                            Description = "gold"
                        },
                        new
                        {
                            CustomerTypeId = 4,
                            Description = "platinum"
                        });
                });

            modelBuilder.Entity("ShipmentStatus", b =>
                {
                    b.Property<int>("ShipmentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shipment_status_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("description");

                    b.HasKey("ShipmentStatusId");

                    b.ToTable("shipment_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            ShipmentStatusId = 1,
                            Description = "Habilitado"
                        },
                        new
                        {
                            ShipmentStatusId = 2,
                            Description = "Empaquetado"
                        },
                        new
                        {
                            ShipmentStatusId = 3,
                            Description = "En Tránsito"
                        },
                        new
                        {
                            ShipmentStatusId = 4,
                            Description = "LlegadaDestino"
                        },
                        new
                        {
                            ShipmentStatusId = 5,
                            Description = "Entregado"
                        },
                        new
                        {
                            ShipmentStatusId = 6,
                            Description = "Devuelto"
                        });
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int>("CustomerTypeId")
                        .HasColumnType("int")
                        .HasColumnName("customer_type_id");

                    b.Property<string>("DocmNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("docm_number");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone");

                    b.HasKey("CustomerId");

                    b.HasIndex("CustomerTypeId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("customers", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CustomerTypeId = 2,
                            DocmNumber = "20123456789",
                            Email = "contacto@acme.com",
                            Name = "Acme Corporation",
                            Phone = "+51987654321"
                        },
                        new
                        {
                            CustomerId = 2,
                            CustomerTypeId = 1,
                            DocmNumber = "20234567890",
                            Email = "ventas@techstore.pe",
                            Name = "TechStore SAC",
                            Phone = "+51976543210"
                        },
                        new
                        {
                            CustomerId = 3,
                            CustomerTypeId = 2,
                            DocmNumber = "20345678901",
                            Email = "info@globalimports.com",
                            Name = "Global Imports EIRL",
                            Phone = "+51965432109"
                        },
                        new
                        {
                            CustomerId = 4,
                            CustomerTypeId = 1,
                            DocmNumber = "12345678",
                            Email = "pedro.sanchez@email.com",
                            Name = "Pedro Sánchez",
                            Phone = "+51954321098"
                        },
                        new
                        {
                            CustomerId = 5,
                            CustomerTypeId = 1,
                            DocmNumber = "20456789012",
                            Email = "ventas@distrilima.pe",
                            Name = "Distribuidora Lima SAC",
                            Phone = "+51943210987"
                        },
                        new
                        {
                            CustomerId = 6,
                            CustomerTypeId = 1,
                            DocmNumber = "23456789",
                            Email = "ana.torres@email.com",
                            Name = "Ana Torres",
                            Phone = "+51932109876"
                        });
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Shipment", b =>
                {
                    b.Property<int>("ShipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shipment_id");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("destination");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("received_at");

                    b.Property<string>("Receivedby")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("received_by");

                    b.Property<int>("ShipmentStatusId")
                        .HasColumnType("int")
                        .HasColumnName("shipment_status_id");

                    b.Property<DateTime>("ShippedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("shipped_at");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tracking_number");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ShipmentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ShipmentStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("shipments", (string)null);

                    b.HasData(
                        new
                        {
                            ShipmentId = 1,
                            CustomerId = 1,
                            Description = "Equipos de cómputo - 5 laptops Dell",
                            Destination = "Av. Arequipa 1234, Miraflores, Lima",
                            ReceivedAt = new DateTime(2024, 12, 22, 14, 15, 0, 0, DateTimeKind.Utc),
                            Receivedby = "Roberto Mendoza",
                            ShipmentStatusId = 5,
                            ShippedAt = new DateTime(2024, 12, 20, 10, 30, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-001",
                            UserId = 2
                        },
                        new
                        {
                            ShipmentId = 2,
                            CustomerId = 2,
                            Description = "Smartphones Samsung Galaxy - 10 unidades",
                            Destination = "Jr. Lampa 456, Cercado de Lima, Lima",
                            Receivedby = "",
                            ShipmentStatusId = 3,
                            ShippedAt = new DateTime(2024, 12, 23, 8, 0, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-002",
                            UserId = 3
                        },
                        new
                        {
                            ShipmentId = 3,
                            CustomerId = 3,
                            Description = "Componentes electrónicos importados",
                            Destination = "Av. Industrial 789, Callao",
                            Receivedby = "",
                            ShipmentStatusId = 4,
                            ShippedAt = new DateTime(2024, 12, 24, 9, 15, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-003",
                            UserId = 2
                        },
                        new
                        {
                            ShipmentId = 4,
                            CustomerId = 4,
                            Description = "Paquete personal - Documentos",
                            Destination = "Calle Los Robles 321, San Isidro, Lima",
                            Receivedby = "",
                            ShipmentStatusId = 2,
                            ShippedAt = new DateTime(2024, 12, 25, 11, 45, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-004",
                            UserId = 4
                        },
                        new
                        {
                            ShipmentId = 5,
                            CustomerId = 5,
                            Description = "Productos de limpieza - 50 cajas",
                            Destination = "Av. Venezuela 555, Breña, Lima",
                            Receivedby = "",
                            ShipmentStatusId = 1,
                            ShippedAt = new DateTime(2024, 12, 26, 7, 30, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-005",
                            UserId = 3
                        },
                        new
                        {
                            ShipmentId = 6,
                            CustomerId = 1,
                            Description = "Impresoras HP LaserJet - 3 unidades",
                            Destination = "Av. Arequipa 1234, Miraflores, Lima",
                            ReceivedAt = new DateTime(2024, 12, 19, 16, 30, 0, 0, DateTimeKind.Utc),
                            Receivedby = "Roberto Mendoza",
                            ShipmentStatusId = 5,
                            ShippedAt = new DateTime(2024, 12, 18, 13, 0, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-006",
                            UserId = 2
                        },
                        new
                        {
                            ShipmentId = 7,
                            CustomerId = 6,
                            Description = "Paquete personal - Ropa",
                            Destination = "Av. Javier Prado 999, San Borja, Lima",
                            Receivedby = "",
                            ShipmentStatusId = 6,
                            ShippedAt = new DateTime(2024, 12, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-007",
                            UserId = 4
                        },
                        new
                        {
                            ShipmentId = 8,
                            CustomerId = 3,
                            Description = "Repuestos automotrices - Caja grande",
                            Destination = "Av. Industrial 789, Callao",
                            Receivedby = "",
                            ShipmentStatusId = 3,
                            ShippedAt = new DateTime(2024, 12, 26, 14, 20, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-008",
                            UserId = 2
                        },
                        new
                        {
                            ShipmentId = 9,
                            CustomerId = 2,
                            Description = "Accesorios de red - Cables UTP Cat6",
                            Destination = "Jr. Lampa 456, Cercado de Lima, Lima",
                            Receivedby = "",
                            ShipmentStatusId = 1,
                            ShippedAt = new DateTime(2024, 12, 26, 15, 0, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-009",
                            UserId = 3
                        },
                        new
                        {
                            ShipmentId = 10,
                            CustomerId = 5,
                            Description = "Papel Bond A4 - 100 millares",
                            Destination = "Av. Venezuela 555, Breña, Lima",
                            Receivedby = "",
                            ShipmentStatusId = 2,
                            ShippedAt = new DateTime(2024, 12, 27, 9, 30, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-010",
                            UserId = 3
                        },
                        new
                        {
                            ShipmentId = 11,
                            CustomerId = 3,
                            Description = "Tarjetas gráficas NVIDIA RTX - 5 unidades",
                            Destination = "Av. Industrial 789, Callao",
                            Receivedby = "",
                            ShipmentStatusId = 3,
                            ShippedAt = new DateTime(2024, 12, 24, 16, 45, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-011",
                            UserId = 2
                        },
                        new
                        {
                            ShipmentId = 12,
                            CustomerId = 1,
                            Description = "Servidores Rack 1U - 2 unidades",
                            Destination = "Av. Arequipa 1234, Miraflores, Lima",
                            Receivedby = "",
                            ShipmentStatusId = 4,
                            ShippedAt = new DateTime(2024, 12, 22, 11, 0, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-012",
                            UserId = 2
                        },
                        new
                        {
                            ShipmentId = 13,
                            CustomerId = 4,
                            Description = "Zapatillas deportivas - Regalo",
                            Destination = "Calle Los Robles 321, San Isidro, Lima",
                            ReceivedAt = new DateTime(2024, 12, 21, 10, 15, 0, 0, DateTimeKind.Utc),
                            Receivedby = "Carlos Ramírez",
                            ShipmentStatusId = 5,
                            ShippedAt = new DateTime(2024, 12, 20, 14, 20, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-013",
                            UserId = 4
                        },
                        new
                        {
                            ShipmentId = 14,
                            CustomerId = 6,
                            Description = "Lote de cosméticos",
                            Destination = "Av. Javier Prado 999, San Borja, Lima",
                            Receivedby = "",
                            ShipmentStatusId = 1,
                            ShippedAt = new DateTime(2024, 12, 27, 8, 10, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-014",
                            UserId = 4
                        },
                        new
                        {
                            ShipmentId = 15,
                            CustomerId = 2,
                            Description = "Tablets Lenovo 10 pulgadas - 20 unidades",
                            Destination = "Jr. Lampa 456, Cercado de Lima, Lima",
                            Receivedby = "",
                            ShipmentStatusId = 3,
                            ShippedAt = new DateTime(2024, 12, 25, 13, 0, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-015",
                            UserId = 3
                        },
                        new
                        {
                            ShipmentId = 16,
                            CustomerId = 5,
                            Description = "Útiles de escritorio al por mayor",
                            Destination = "Av. Venezuela 555, Breña, Lima",
                            ReceivedAt = new DateTime(2024, 12, 20, 9, 30, 0, 0, DateTimeKind.Utc),
                            Receivedby = "Jefe Almacén",
                            ShipmentStatusId = 5,
                            ShippedAt = new DateTime(2024, 12, 19, 10, 0, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-016",
                            UserId = 3
                        },
                        new
                        {
                            ShipmentId = 17,
                            CustomerId = 1,
                            Description = "Proyectores Epson - 4 unidades",
                            Destination = "Av. Arequipa 1234, Miraflores, Lima",
                            Receivedby = "",
                            ShipmentStatusId = 2,
                            ShippedAt = new DateTime(2024, 12, 26, 17, 30, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-017",
                            UserId = 2
                        },
                        new
                        {
                            ShipmentId = 18,
                            CustomerId = 3,
                            Description = "Memorias RAM DDR5 32GB - 50 unidades",
                            Destination = "Av. Industrial 789, Callao",
                            Receivedby = "",
                            ShipmentStatusId = 4,
                            ShippedAt = new DateTime(2024, 12, 23, 15, 45, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-018",
                            UserId = 2
                        },
                        new
                        {
                            ShipmentId = 19,
                            CustomerId = 4,
                            Description = "Colección de libros de historia",
                            Destination = "Calle Los Robles 321, San Isidro, Lima",
                            ReceivedAt = new DateTime(2024, 12, 18, 16, 20, 0, 0, DateTimeKind.Utc),
                            Receivedby = "Portería",
                            ShipmentStatusId = 5,
                            ShippedAt = new DateTime(2024, 12, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-019",
                            UserId = 4
                        },
                        new
                        {
                            ShipmentId = 20,
                            CustomerId = 6,
                            Description = "Ropa de invierno - Devolución",
                            Destination = "Av. Javier Prado 999, San Borja, Lima",
                            Receivedby = "",
                            ShipmentStatusId = 6,
                            ShippedAt = new DateTime(2024, 12, 21, 11, 15, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-020",
                            UserId = 4
                        },
                        new
                        {
                            ShipmentId = 21,
                            CustomerId = 2,
                            Description = "Cámaras de seguridad IP - Kit completo",
                            Destination = "Jr. Lampa 456, Cercado de Lima, Lima",
                            Receivedby = "",
                            ShipmentStatusId = 1,
                            ShippedAt = new DateTime(2024, 12, 27, 10, 0, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-021",
                            UserId = 3
                        },
                        new
                        {
                            ShipmentId = 22,
                            CustomerId = 5,
                            Description = "Detergente industrial - 20 bolsas",
                            Destination = "Av. Venezuela 555, Breña, Lima",
                            Receivedby = "",
                            ShipmentStatusId = 2,
                            ShippedAt = new DateTime(2024, 12, 27, 12, 30, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-022",
                            UserId = 3
                        },
                        new
                        {
                            ShipmentId = 23,
                            CustomerId = 1,
                            Description = "Licencias de Software en físico",
                            Destination = "Av. Arequipa 1234, Miraflores, Lima",
                            Receivedby = "",
                            ShipmentStatusId = 3,
                            ShippedAt = new DateTime(2024, 12, 24, 14, 0, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-023",
                            UserId = 2
                        },
                        new
                        {
                            ShipmentId = 24,
                            CustomerId = 3,
                            Description = "Discos Duros 4TB NAS - 10 unidades",
                            Destination = "Av. Industrial 789, Callao",
                            ReceivedAt = new DateTime(2024, 12, 22, 11, 10, 0, 0, DateTimeKind.Utc),
                            Receivedby = "Seguridad Almacén",
                            ShipmentStatusId = 5,
                            ShippedAt = new DateTime(2024, 12, 20, 8, 45, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-024",
                            UserId = 2
                        },
                        new
                        {
                            ShipmentId = 25,
                            CustomerId = 4,
                            Description = "Juguetes varios para donación",
                            Destination = "Calle Los Robles 321, San Isidro, Lima",
                            Receivedby = "",
                            ShipmentStatusId = 4,
                            ShippedAt = new DateTime(2024, 12, 23, 18, 0, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-025",
                            UserId = 4
                        },
                        new
                        {
                            ShipmentId = 26,
                            CustomerId = 6,
                            Description = "Accesorios de cocina - Ollas y sartenes",
                            Destination = "Av. Javier Prado 999, San Borja, Lima",
                            Receivedby = "",
                            ShipmentStatusId = 1,
                            ShippedAt = new DateTime(2024, 12, 27, 14, 20, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-026",
                            UserId = 4
                        },
                        new
                        {
                            ShipmentId = 27,
                            CustomerId = 2,
                            Description = "Monitores Curvos 27'' - 6 unidades",
                            Destination = "Jr. Lampa 456, Cercado de Lima, Lima",
                            Receivedby = "",
                            ShipmentStatusId = 3,
                            ShippedAt = new DateTime(2024, 12, 25, 10, 10, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-027",
                            UserId = 3
                        },
                        new
                        {
                            ShipmentId = 28,
                            CustomerId = 5,
                            Description = "Café en grano selección - 20kg",
                            Destination = "Av. Venezuela 555, Breña, Lima",
                            ReceivedAt = new DateTime(2024, 12, 22, 8, 45, 0, 0, DateTimeKind.Utc),
                            Receivedby = "Recepcionista",
                            ShipmentStatusId = 5,
                            ShippedAt = new DateTime(2024, 12, 21, 9, 30, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-028",
                            UserId = 3
                        },
                        new
                        {
                            ShipmentId = 29,
                            CustomerId = 1,
                            Description = "Laptops HP Omen Gaming - 2 unidades",
                            Destination = "Av. Arequipa 1234, Miraflores, Lima",
                            Receivedby = "",
                            ShipmentStatusId = 2,
                            ShippedAt = new DateTime(2024, 12, 26, 16, 0, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-029",
                            UserId = 2
                        },
                        new
                        {
                            ShipmentId = 30,
                            CustomerId = 3,
                            Description = "Procesadores Intel i9 - Defectuosos",
                            Destination = "Av. Industrial 789, Callao",
                            Receivedby = "",
                            ShipmentStatusId = 6,
                            ShippedAt = new DateTime(2024, 12, 19, 13, 15, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-030",
                            UserId = 2
                        },
                        new
                        {
                            ShipmentId = 31,
                            CustomerId = 4,
                            Description = "Documentos legales urgentes",
                            Destination = "Calle Los Robles 321, San Isidro, Lima",
                            ReceivedAt = new DateTime(2024, 12, 22, 15, 30, 0, 0, DateTimeKind.Utc),
                            Receivedby = "Pedro Sánchez",
                            ShipmentStatusId = 5,
                            ShippedAt = new DateTime(2024, 12, 22, 11, 45, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-031",
                            UserId = 4
                        },
                        new
                        {
                            ShipmentId = 32,
                            CustomerId = 6,
                            Description = "Muebles pequeños (Mesas de noche)",
                            Destination = "Av. Javier Prado 999, San Borja, Lima",
                            Receivedby = "",
                            ShipmentStatusId = 1,
                            ShippedAt = new DateTime(2024, 12, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-032",
                            UserId = 4
                        },
                        new
                        {
                            ShipmentId = 33,
                            CustomerId = 2,
                            Description = "Audífonos Bluetooth Noise Cancelling",
                            Destination = "Jr. Lampa 456, Cercado de Lima, Lima",
                            Receivedby = "",
                            ShipmentStatusId = 3,
                            ShippedAt = new DateTime(2024, 12, 24, 15, 30, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-033",
                            UserId = 3
                        },
                        new
                        {
                            ShipmentId = 34,
                            CustomerId = 5,
                            Description = "Cajas de galletas y snacks",
                            Destination = "Av. Venezuela 555, Breña, Lima",
                            Receivedby = "",
                            ShipmentStatusId = 4,
                            ShippedAt = new DateTime(2024, 12, 23, 10, 20, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-034",
                            UserId = 3
                        },
                        new
                        {
                            ShipmentId = 35,
                            CustomerId = 1,
                            Description = "Estabilizadores de voltaje industriales",
                            Destination = "Av. Arequipa 1234, Miraflores, Lima",
                            ReceivedAt = new DateTime(2024, 12, 21, 14, 0, 0, 0, DateTimeKind.Utc),
                            Receivedby = "Roberto Mendoza",
                            ShipmentStatusId = 5,
                            ShippedAt = new DateTime(2024, 12, 20, 11, 0, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-035",
                            UserId = 2
                        },
                        new
                        {
                            ShipmentId = 36,
                            CustomerId = 3,
                            Description = "Placas madre ASUS ROG - 8 unidades",
                            Destination = "Av. Industrial 789, Callao",
                            Receivedby = "",
                            ShipmentStatusId = 2,
                            ShippedAt = new DateTime(2024, 12, 27, 16, 45, 0, 0, DateTimeKind.Utc),
                            TrackingNumber = "TRK-2024-036",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Tracker.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@tracker.com",
                            IsActive = true,
                            Name = "Admin User",
                            PasswordHash = "$2a$10$U1Et/gitorJ8ogzMkWQl6OoMrqrjUR.iAPG5eRBtZFNBDRSA1XJYq",
                            Role = 3
                        },
                        new
                        {
                            UserId = 2,
                            Email = "juan.perez@tracker.com",
                            IsActive = true,
                            Name = "Juan Pérez",
                            PasswordHash = "$2a$10$U1Et/gitorJ8ogzMkWQl6OoMrqrjUR.iAPG5eRBtZFNBDRSA1XJYq",
                            Role = 2
                        },
                        new
                        {
                            UserId = 3,
                            Email = "maria.gonzalez@tracker.com",
                            IsActive = true,
                            Name = "María González",
                            PasswordHash = "$2a$10$U1Et/gitorJ8ogzMkWQl6OoMrqrjUR.iAPG5eRBtZFNBDRSA1XJYq",
                            Role = 1
                        },
                        new
                        {
                            UserId = 4,
                            Email = "carlos.ramirez@tracker.com",
                            IsActive = true,
                            Name = "Carlos Ramírez",
                            PasswordHash = "$2a$10$U1Et/gitorJ8ogzMkWQl6OoMrqrjUR.iAPG5eRBtZFNBDRSA1XJYq",
                            Role = 1
                        });
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Customer", b =>
                {
                    b.HasOne("CustomerType", "CustomerType")
                        .WithMany()
                        .HasForeignKey("CustomerTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomerType");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Shipment", b =>
                {
                    b.HasOne("Tracker.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShipmentStatus", "ShipmentStatus")
                        .WithMany()
                        .HasForeignKey("ShipmentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tracker.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ShipmentStatus");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
